# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.CharField(max_length=200)),
                ('id2', models.CharField(max_length=200)),
                ('action1', models.IntegerField()),
                ('action2', models.IntegerField()),
                ('competition_id', models.CharField(max_length=400)),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
